Proyecto_Kujo-main/Frontend/Jojo.WebUI/Jojo.WebUI/Models/FacturaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Jojo.WebUI.Models
{
    public class FacturaViewModel
    {

        [Display(Name = "Id")]
        public int fact_Id { get; set; }
        [Display(Name = "Cliente")]
        public int? clie_Id { get; set; }
        [Display(Name = "Empleado")]
        public int? empl_Id { get; set; }

        [Display(Name = "Fecha Compra")]
        public DateTime? fact_fechacompra { get; set; }

        [NotMapped]
        [Display(Name = "Nombre Empleado")]
        public string NombreEmpleado { get; set; }

        [NotMapped]
        [Display(Name = "Nombre Cliente")]
        public string NombreCliente { get; set; }

        [NotMapped]
        public string prod_Id { get; set; }

        [NotMapped]
        [Display(Name = "Producto")]
        public string prod_Descripcion { get; set; }

        [NotMapped]
        public string SubTotal { get; set; }

        [NotMapped]
        public string IVA { get; set; }

        [NotMapped]
        public string Total { get; set; }

        public bool? fact_estadocompra { get; set; }
        [Display(Name = "Estado")]
        public bool? fact_Estado { get; set; }
        [Display(Name = "Fecha de creación")]
        public int fact_UserCrea { get; set; }
        [Display(Name = "Usuario creador")]
        public string empl_Crea { get; set; }
        [Display(Name = "Fecha de creación")]
        public DateTime fact_FechaCreacion { get; set; }
        [Display(Name = "Último usuario modificador")]
        public int? fact_UserModifica { get; set; }
        [Display(Name = "Último usuario modificador")]
        public string empl_Modifica { get; set; }
        [Display(Name = "Última fecha de modificación")]
        public DateTime? fact_FechaModificacion { get; set; }

        public int IdNueva { get; set; }

        public string FacturasPorcentaje { get; set; }

        public string FacturasTotales { get; set; }

        [Display(Name = "Total por día")]
        public string Total_Dia { get; set; }
        [Display(Name = "IVA por día")]
        public string IVA_Dia { get; set; }
        [Display(Name = "SubTotal por día")]
        public string SubTotal_Dia { get; set; }
        [Display(Name = "Fecha")]
        public string Fecha { get; set; }

    }
}

Proyecto_Kujo-main/Frontend/Jojo.WebUI/Jojo.WebUI/Controllers/FacturasController.cs
using Jojo.WebUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Jojo.WebUI.Controllers
{
    public class FacturasController : Controller
    {
        private static string _baseurl;

        public FacturasController()
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            _baseurl = builder.GetSection("ApiSettings:BaseUrl").Value;

        }


        [HttpGet("Facturas/Listado")]
        public async Task<IActionResult> Index()
        {
            List<FacturaViewModel> listado = new List<FacturaViewModel>();

            using (var httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync(_baseurl + "api/Facturas/Listado");
                if (response.IsSuccessStatusCode)
                {
                    var jsonResponse = await response.Content.ReadAsStringAsync();
                    listado = JsonConvert.DeserializeObject<List<FacturaViewModel>>(jsonResponse);
                }

                return View(listado);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            List<FacturaDetalleViewModel> listado = new List<FacturaDetalleViewModel>();


            using (var httpClient = new HttpClient())
            {

                var responseprod = await httpClient.GetAsync(_baseurl + "api/Productos/Listado");
                var responseclie = await httpClient.GetAsync(_baseurl + "api/Clientes/Listado");


                if (responseprod.IsSuccessStatusCode)
                {
                    var jsonResponseP = await responseprod.Content.ReadAsStringAsync();
                    JArray jArray = JArray.Parse(jsonResponseP);
                    ViewBag.prod_Id = new SelectList(jArray, "prod_Id", "prod_Descripcion");
                }

                if (responseclie.IsSuccessStatusCode)
                {
                    var jsonResponseC = await responseclie.Content.ReadAsStringAsync();
                    JArray jArray = JArray.Parse(jsonResponseC);
                    ViewBag.clie_Id = new SelectList(jArray, "clie_Id", "nombreCliente");
                }

                if (string.IsNullOrEmpty(HttpContext.Session.GetInt32("NuevoID").ToString()) || string.IsNullOrEmpty(HttpContext.Session.GetInt32("Cliente").ToString()) || (!string.IsNullOrEmpty(HttpContext.Session.GetInt32("Cliente").ToString()) && HttpContext.Session.GetInt32("Cliente") == 0))
                {
                    ViewBag.NuevoId = 0;
                    ViewBag.Subtotal = 0;
                    ViewBag.IVA = 0;
                    ViewBag.Total = 0;

                    var responsetabla = await httpClient.GetAsync(_baseurl + "api/FacturaDetalles/Listado?id=" + 0);
                    if (responsetabla.IsSuccessStatusCode)
                    {
                        var jsonResponse = await responsetabla.Content.ReadAsStringAsync();
                        listado = JsonConvert.DeserializeObject<List<FacturaDetalleViewModel>>(jsonResponse);
                        ViewBag.Detalles = listado;
                    }

                }
                if (!string.IsNullOrEmpty(HttpContext.Session.GetInt32("NuevoID").ToString()) || (!string.IsNullOrEmpty(HttpContext.Session.GetInt32("Cliente").ToString()) && HttpContext.Session.GetInt32("Cliente") != 0))
                {
                    var jsonResponseC = await responseclie.Content.ReadAsStringAsync();
                    JArray jArray = JArray.Parse(jsonResponseC);
                    ViewBag.clie_Id = new SelectList(jArray, "clie_Id", "nombreCliente", HttpContext.Session.GetInt32("Cliente"));
                    ViewBag.NuevoId = HttpContext.Session.GetString("NuevoID");

                    var responsetabla = await httpClient.GetAsync(_baseurl + "api/FacturaDetalles/Listado?id=" + int.Parse(HttpContext.Session.GetString("NuevoID")));
                    if (responsetabla.IsSuccessStatusCode)
                    {
                        var jsonResponse = await responsetabla.Content.ReadAsStringAsync();
                        listado = JsonConvert.DeserializeObject<List<FacturaDetalleViewModel>>(jsonResponse);
                        ViewBag.Detalles = listado;
                    }

                    var responseDetalles = await httpClient.GetAsync(_baseurl + "api/FacturaDetalles/Detalles?id=" + int.Parse(HttpContext.Session.GetString("NuevoID")));
                    if (responsetabla.IsSuccessStatusCode)
                    {
                        var jsonResponse = await responseDetalles.Content.ReadAsStringAsync();
                        JObject jsonObjGet = JObject.Parse(jsonResponse);
                        JArray jsonArray = JArray.Parse(jsonObjGet["data"].ToString());
                        FacturaViewModel detalles = JsonConvert.DeserializeObject<FacturaViewModel>(jsonArray[0].ToString());
                        ViewBag.Subtotal = detalles.SubTotal;
                        ViewBag.IVA = detalles.IVA;
                        ViewBag.Total = detalles.Total;

                    }
                }
                return View();
            }
        }

        public IActionResult Terminar()
        {

            HttpContext.Session.SetString("NuevoID", "");
            HttpContext.Session.SetInt32("Cliente", 0);


            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create(FacturaViewModel fact)
        {
            fact.empl_Id = (int)HttpContext.Session.GetInt32("empl_Id");
            fact.fact_UserCrea = (int)HttpContext.Session.GetInt32("UsuarioId");
            List<FacturaDetalleViewModel> listado = new List<FacturaDetalleViewModel>();

            HttpContext.Session.SetInt32("Cliente", (int)fact.clie_Id);


            using (var httpClient = new HttpClient())
            {
                var json = JsonConvert.SerializeObject(fact);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await httpClient.PostAsync(_baseurl + "api/Facturas/Insert", content);

                if (response.IsSuccessStatusCode)
                {

                    var jsonResponse = await response.Content.ReadAsStringAsync();
                    JObject jsonObjGet = JObject.Parse(jsonResponse);
                    JArray jsonArray = JArray.Parse(jsonObjGet["data"].ToString());

                    FacturaViewModel factu = JsonConvert.DeserializeObject<FacturaViewModel>(jsonArray[0].ToString());

                    var responseprod = await httpClient.GetAsync(_baseurl + "api/Productos/Listado");
                    var responseclie = await httpClient.GetAsync(_baseurl + "api/Clientes/Listado");
                    var responsetabla = await httpClient.GetAsync(_baseurl + "api/FacturaDetalles/Listado?id=" + 0);


                    if (responseprod.IsSuccessStatusCode)
                    {
                        var jsonResponseP = await responseprod.Content.ReadAsStringAsync();
                        JArray jArray = JArray.Parse(jsonResponseP);
                        ViewBag.prod_Id = new SelectList(jArray, "prod_Id", "prod_Descripcion");
                    }

                    if (responseclie.IsSuccessStatusCode)
                    {
                        var jsonResponseC = await responseclie.Content.ReadAsStringAsync();
                        JArray jArray = JArray.Parse(jsonResponseC);
                        ViewBag.clie_Id = new SelectList(jArray, "clie_Id", "nombreCliente", factu.clie_Id);
                    }

                    if (responsetabla.IsSuccessStatusCode)
                    {
                        var jsonResponseT = await responsetabla.Content.ReadAsStringAsync();
                        listado = JsonConvert.DeserializeObject<List<FacturaDetalleViewModel>>(jsonResponseT);
                        ViewBag.Detalles = listado;
                    }

                    HttpContext.Session.SetString("NuevoID", factu.fact_Id.ToString());
                    ViewBag.Subtotal = 0;
                    ViewBag.IVA = 0;
                    ViewBag.Total = 0;
                    ViewBag.NuevoId = HttpContext.Session.GetString("NuevoID");

                    return View();
                }
                else
                {
                    return View();
                }
            }
        }


        [HttpPost]
        public async Task<IActionResult> CreateFactDet(string NuevaId, int prod_Id, decimal txtPrecio, int txtCantidad)
        {

            FacturaDetalleViewModel factdet = new FacturaDetalleViewModel();
            factdet.fact_Id = Convert.ToInt32(NuevaId);
            factdet.prod_Id = prod_Id;
            factdet.facd_PrecioUnitario = txtPrecio;
            factdet.prod_Cantidad = txtCantidad;
            factdet.facd_UserCrea = (int)HttpContext.Session.GetInt32("UsuarioId");



            using (var httpClient = new HttpClient())
            {
                var json = JsonConvert.SerializeObject(factdet);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await httpClient.PostAsync(_baseurl + "api/FacturaDetalles/Insert", content);

                if (response.IsSuccessStatusCode)
                {

                    var responseprod = await httpClient.GetAsync(_baseurl + "api/Productos/Listado");
                    var responseclie = await httpClient.GetAsync(_baseurl + "api/Clientes/Listado");


                    if (responseprod.IsSuccessStatusCode)

Proyecto_Kujo-main/Frontend/Jojo.WebUI/Jojo.WebUI/Views/Facturas/Create.cshtml
@model Jojo.WebUI.Models.FacturaViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nueva</h1>

<h4>Factura</h4>
<hr />
<div class="row">
    <div class="col-sm-5">
        <div class="card" style="box-shadow: 0px 0px 6px 4px;">
            <div class="card-header"></div>
            <div class="card-body">
                <div class="row pb-4">
                    <form asp-action="Create" id="createform">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="clie_Id" class="control-label"></label>
                            <select asp-for="clie_Id" id="clie_Id" onchange="CambioId()" class="form-control" asp-items="ViewBag.clie_Id">
                                <option value="">Elige un cliente</option>
                            </select>
                        </div>
                        <div class="form-group mt-5">
                            <input type="button" id="btn-create" value="Crear Factura" onclick="CrearFactura()" class="btn btn-primary" />
                            <input type="button" id="Cancelar_Venta" value="Cancelar Venta" onclick="CancelarFactura()" class="btn btn-danger" />
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>


    <div class="col-sm-7">

        <div class="card" style="box-shadow: 0px 0px 6px 4px;">
            <div class="card-header"></div>
            <div class="card-body">

                <form action="@Url.Action("CreateFactDet","Facturas")" id="Detallesform" method="post">
                    <input type="hidden" id="NuevaId" name="NuevaId" value="@ViewBag.NuevoId" />
                    <div class="row">
                        <div class="col-sm-6">
                            <label class="control-label">Producto</label>
                            <select class="form-control" asp-items="ViewBag.prod_Id" id="prod_Id" name="prod_Id" disabled>
                                <option value="">Elige un producto</option>
                            </select>

                        </div>
                        <div class="col-sm-6">
                            <label class="control-label">Precio</label>
                            <input type="hidden" id="PrecioHidden" name="txtPrecio" />
                            <input type="text" class="form-control" id="txtPrecio" disabled />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <label class="control-label">Cantidad</label>
                            <input type="number" class="form-control" id="txtCantidad" name="txtCantidad" disabled />
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="button" id="btnAgregarProducto" value="Agregar" onclick="ValidarDetalle()" class="btn btn-primary" disabled />
                        <input type="button" id="TerminarVenta" value="Terminar Factura" onclick="TerminarFactura()" class="btn btn-info" disabled />
                    </div>

                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>


<div class="mt-5">
    <table class="table" id="DataTable">
        <thead class="bg-dark">
            <tr>
                <th class="text-light text-center">
                    Id
                </th>
                <th class="text-light text-center">
                    Producto
                </th>
                <th class="text-light text-center">
                    Precio
                </th>
                <th class="text-light text-center">
                    Cantidad
                </th>
                <th class="text-light text-center">
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody id="tbodyVentas">
            @foreach (var item in ViewBag.Detalles)
            {
                <tr>
                    <td>
                        @item.facd_Id
                    </td>
                    <td>
                        @item.prod_Descripcion
                    </td>
                    <td>
                        @item.facd_PrecioUnitario
                    </td>
                    <td>
                        @item.prod_Cantidad
                    </td>
                    <td>
                        <button class="btn btn-outline-danger" onclick=ModalDelete(@item.facd_Id)><i class='icon pli-trash'></i></button>
                    </td>

                </tr>
            }

        </tbody>
    </table>

    <div class="row mt-2">
        <div class="col-sm-4">
            <label>SubTotal</label>
            <input class="form-control border-dark" type="text" id="txtSubTotal" value="@ViewBag.Subtotal" disabled />
        </div>
        <div class="col-sm-4">
            <label>IVA</label>
            <input class="form-control border-dark" type="text" id="txtIVA" value="@ViewBag.IVA" disabled />
        </div>
        <div class="col-sm-4">
            <label>Total</label>
            <input class="form-control border-dark" type="text" id="txtTotal" value="@ViewBag.Total" disabled />
        </div>
    </div>
</div>


@*Delete*@
<div class="modal fade" id="ModalDelete" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTopTitle"></h5>
            </div>
            <form action="@Url.Action("DeleteDetails","Facturas")" method="post" id="FD">
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <input type="hidden"
                                   id="idD"
                                   class="form-control"
                                   name="idD" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 text-center h4">
                            <h4 class="padding-top-30 mb-30 weight-500">¿Desea Eliminar Este Registro?</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <button type="submit" class="btn btn-primary border-radius-100 btn-block confirmation-btn" data-dismiss="modal">Cancelar<i class="la la-ban"></i></button>
                        </div>
                        <div class="col-6">
                            <button type="button" onclick="Ingresar3()" class="btn btn-danger border-radius-100 btn-block confirmation-btn" data-dismiss="modal">Eliminar<i class="bx bx-trash"></i></button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>

        $(document).ready(function () {


            $('#DataTable').dataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.13.2/i18n/es-MX.json"
                },

            });



            var NuevaFacturaId = $("#NuevaId").val();
            if ($("#NuevaId").val() == "" || $("#NuevaId").val() == null) {
                NuevaFacturaId = 0
            }




            var cat = sessionStorage.getItem("Insert");
            var cliente = sessionStorage.getItem("Cliente");


            if (cat == "123") {
                $("#prod_Id").attr("disabled", false);
                $("#txtCantidad").attr("disabled", false);
                $("#btnAgregarProducto").attr("disabled", false);
                $("#TerminarVenta").attr("disabled", false);



                $("#clie_Id").attr("disabled", true);
                $("#btn-create").attr("disabled", true);
                $("#Cancelar_Venta").attr("disabled", true);

            }

            if (cliente != null || cliente != "") {
                $("#clie_Id").val(cliente)
            }




        });


        @* CREAR FACTURA *@
        function CrearFactura() {

            if ($("#clie_Id").val() == "") {
                iziToast.warning({
                    title: 'Advertencia',
                    message: 'Es necesario un cliente para la factura',
                    position: 'topRight',
                });
            }
            else {
                sessionStorage.setItem("Insert", "123");
                sessionStorage.setItem("Cliente", $("#clie_Id").val());

                $("#createform").submit();
            }

        }


        @* PRECIO *@
        $("#prod_Id").change(function () {


            var prod_Id = $("#prod_Id").val();

            $.ajax({
                type: "POST",
                url: "/Facturas/PrecioProducto",
                data: { id: prod_Id },
                dataType: "json",
                success: function (response) {
                    console.log(response);
                    var precioSelect = $('#txtPrecio');
                    precioSelect.empty();
                    $.each(response, function (i, value) {
                        console.log(value.prod_Precio);
                        $('#txtPrecio').val(value.prod_Precio);
                        $('#PrecioHidden').val(value.prod_Precio);
                    });

                },
                error: function (xhr, status, error) {
                    console.log("adios");
                }
            });
        });


        @* CANCELAR FACTURA *@
        function CancelarFactura() {
            sessionStorage.clear();
            $("#NuevaId").val("0");
            window.location = "/Facturas/Listado";
        }



        @* VALIDAR DETALLE *@

        function ValidarDetalle() {
            var insertar = true;

            if ($("#prod_Id").val() == "") {
                iziToast.warning({
                    title: 'Advertencia',
                    message: 'El Campo producto es requerido',
                    position: 'topRight',
                });
                insertar = false;
            }

            if ($("#txtCantidad").val() == "" || $("#txtCantidad").val() == null)
            {
                iziToast.warning({
                    title: 'Advertencia',
                    message: 'El Campo cantidad es requerido',
                    position: 'topRight',
                });
                insertar = false;
            }

            if (insertar) {
                $("#Detallesform").submit();
            }

        }

        @* Terminar Factura DETALLE *@
        function TerminarFactura() {
            sessionStorage.clear();
            $("#NuevaId").val("0");
            sessionStorage.setItem("Insert", "321");
            window.location = '/Facturas/Terminar/'
        }

        function ModalDelete(id) {
            $("#idD").val(id);
            $("#ModalDelete").modal("show");
        }
        function Ingresar3() {
            $("#FD").submit();
        }

</script>

Proyecto_Kujo-main/Frontend/Jojo.WebUI/Jojo.WebUI/Views/Facturas/Details.cshtml
@model Jojo.WebUI.Models.FacturaViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles</h1>
<div>

    <div class="row">
        <div class="col-sm-3">
            <label class="font-weight-bold">Id</label><br />
            @Html.DisplayFor(model => model.fact_Id)
        </div>
        <div class="col-sm-3">
            <label class="font-weight-bold">Cliente</label><br />
            <label>@Html.DisplayFor(model => model.NombreCliente)</label>
        </div>
        <div class="col-sm-3">
            <label class="font-weight-bold">Empleado</label><br />
            <label>@Html.DisplayFor(model => model.NombreEmpleado)</label>
        </div>
        <div class="col-sm-3">
            <br />
            <label class="font-weight-bold">Fecha Compra</label><br />
            @Html.DisplayFor(model => model.fact_fechacompra)
        </div>
    </div>
</div>

<div class="mt-5">
    <table class="table" id="DataTable">
        <thead class="bg-dark">
            <tr>
                <th class="text-light text-center">
                    Id
                </th>
                <th class="text-light text-center">
                    Producto
                </th>
                <th class="text-light text-center">
                    Precio
                </th>
                <th class="text-light text-center">
                    Cantidad
                </th>
            </tr>
        </thead>
        <tbody id="tbodyVentas">
            @foreach (var item in ViewBag.Detalles)
            {
                <tr>
                    <td>
                        @item.facd_Id
                    </td>
                    <td>
                        @item.prod_Descripcion
                    </td>
                    <td>
                        @item.facd_PrecioUnitario
                    </td>
                    <td>
                        @item.prod_Cantidad
                    </td>
                </tr>
            }

        </tbody>
    </table>

    <div class="row mt-2">
        <div class="col-sm-4">
            <label>SubTotal</label>
            <input class="form-control border-dark" type="text" id="txtSubTotal" value="@ViewBag.Subtotal" disabled />
        </div>
        <div class="col-sm-4">
            <label>IVA</label>
            <input class="form-control border-dark" type="text" id="txtIVA" value="@ViewBag.IVA" disabled />
        </div>
        <div class="col-sm-4">
            <label>Total</label>
            <input class="form-control border-dark" type="text" id="txtTotal" value="@ViewBag.Total" disabled />
        </div>
    </div>
</div>

<div>
    <br />
    <a class="btn btn-info" asp-action="Index">Regresar</a>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
    $(document).ready(function () {
        $('#DataTable').dataTable({
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.13.2/i18n/es-ES.json"
            },

        });
    });
</script>

Proyecto_Kujo-main/Frontend/Jojo.WebUI/Jojo.WebUI/Views/Facturas/Index.cshtml
@model IEnumerable<Jojo.WebUI.Models.FacturaViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Facturas</h1>



<p>
    <a asp-action="Create" class="btn btn-primary mb-2">Nuevo <i class="pli-add"></i></a>
</p>
<table class="table table-responsive" id="DataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.fact_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fact_fechacompra)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreEmpleado)
            </th>
            <th>
                Acciones
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.fact_Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fact_fechacompra)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreEmpleado)
                </td>
                <td>
                    <a class="EstaListo btn btn-outline-warning"><i class='icon pli-pen-4'></i></a>
                    @Html.ActionLink("", "Details", new { id = item.fact_Id }, new { @class = "btn btn-outline-info pli-eye-visible" })
                    <a class="EliminarFake btn-delete btn btn-outline-danger"><i class='icon pli-trash'></i></a>

                    @*<a class="btn-delete btn btn-danger" data-id="@item.fact_Id">Eliminar</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="~/js/app/Tienda/Facturas.js"></script>